supplementalSpecification: ''
supplementalSpecificationFor:
    BrAPI-Core: ''
separateByModule: true
generateNewRequest: true
generateNewRequestFor:
    AlleleMatrix: false
    BreedingMethod: false
    Call: false
    CallSet: false
    Event: false
    GenomeMap: false
    MarkerPosition: false
    Reference: false
    PedigreeNode: false
    PlannedCross: false
    Season: false
    ServerInfo: false
    Variant: false
    VariantSet: false
newRequestNameFormat: "%sNewRequest"
singleResponseNameFormat: "%sSingleResponse"
listResponseNameFormat: "%sListResponse"
searchRequestNameFormat: "%sSearchRequest"
pluralFor:
    AlleleMatrix: AlleleMatrix
    ServerInfo: ServerInfo
pathItemNameFor:
    AlleleMatrix: /allelematrix
    GenomeMap: /maps
    GermplasmAttribute: /attributes
    GermplasmAttributeValue: /attributevalues
    ObservationUnitHierarchyLevel: /observationlevels
    ObservationVariable: /variables
    PedigreeNode: /pedigree
    ServerInfo: /serverInfo
pathItemNameForProperty:
    GermplasmAttribute:
        attributeCategory:
            /attributes/categories
    Study:
        studyType:
            /studytypes
tagFor:
    BreedingMethod: Germplasm
    PlannedCross: Crosses
singleGet:
    generate: true
    summaryFormat: Get the details of a specific %s
    descriptionFormat: Get details for a %s
    generateFor:
        AlleleMatrix: false
        Call: false
        Cross: false
        Event: false
        MarkerPosition: false
        ObservationUnitHierarchyLevel: false
        PedigreeNode: false
        PlannedCross: false
        ServerInfo: false
listGet:
    generate: true
    summaryFormat: Get a filtered list of %s
    descriptionFormat: Get a list of %s
    generateFor:
        AlleleMatrix: false
        ServerInfo: false
    pagedDefault: true
    paged:
        BreedingMethod: false
    inputFor:
        BreedingMethod: false
    propertiesFromRequest: true
    propertyFromRequestFor:
        GermplasmAttribute:
            germplasmNames: false
            programNames: false
            studyDbId: false
            studyDbIds: false
            studyNames: false
            trialDbIds: false
            trialNames: false
            ontologyDbIds: false
            dataTypes: false
            traitClasses: false
            traitAttributes: false
            traitAttributePUIs: false
            traitEntities: false
            traitEntityPUIs: false
search:
    generate: true
    summaryFormat: Submit a search request for `%s`
    descriptionFormat: Submit a search request for `%s`t
    searchIdFieldName: searchResultsDbId
    submitDescriptionFormat:  |-
        Submit a search request for `%s`<br/>
        Search requests allow a client to send a complex query for data. However, the server may not respond with the search results immediately. 
        If a server needs more time to process the request, it might respond with a `searchResultsDbId`. 
        Use the corresponding `GET /search/%s/{searchResultsDbId}` to retrieve the results of the search. <br/> 
        Review the <a target="_blank" href="https://wiki.brapi.org/index.php/Search_Services#POST_Search_Entity">Search Services documentation</a> for additional implementation details.
    retrieveDescriptionFormat: |-
        Get the results of a `%s` search request <br/>
        Clients should submit a search request using the corresponding `POST /search/%s` endpoint.
        Search requests allow a client to send a complex query for data. However, the server may not respond with the search results immediately. 
        If a server needs more time to process the request, it might respond with a `searchResultsDbId`. 
        Use this endpoint to retrieve the results of the search. <br/> 
        Review the <a target="_blank" href="https://wiki.brapi.org/index.php/Search_Services#POST_Search_Entity">Search Services documentation</a> for additional implementation details.
    generateFor:
        BreedingMethod: false
        Cross: false
        CrossingProject: false
        Event: false
        GenomeMap: false
        Method: false
        ObservationUnitHierarchyLevel: false
        Ontology: false
        PlannedCross: false
        Scale: false
        Season: false
        SeedLot: false
        ServerInfo: false
        Trait: false
post:
    generate: true
    summaryFormat: Create new %s
    descriptionFormat: Add new %s to database
    generateFor:
        AlleleMatrix: false
        BreedingMethod: false
        Call: false
        CallSet: false
        Event: false
        GenomeMap: false
        MarkerPosition: false
        ObservationUnitHierarchyLevel: false
        Reference: false
        ReferenceSet: false
        ServerInfo: false
        Variant: false
        VariantSet: false
put:
    generate: true
    summaryFormat: Update the details for an existing %s
    descriptionFormat: Update the details for an existing %s
    generateFor:
        AlleleMatrix: false
        BreedingMethod: false
        Call: false
        CallSet: false
        Event: false
        GenomeMap: false
        MarkerPosition: false
        ObservationUnitHierarchyLevel: false
        Reference: false
        ReferenceSet: false
        PedigreeNode: false
        Plate: false
        ServerInfo: false
        Variant: false
        VariantSet: false
    multiple: false
    multipleFor:
        Call: true
        Cross: true
        Observation: true
        ObservationUnit: true
        PlannedCross: true
        PedigreeNode: true
        Plate: true
        Sample: true
delete:
    generate: false
    summaryFormat: Delete an existing %s
    descriptionFormat: Delete existing %s
    generateFor:
        AlleleMatrix: false
        Call: false
        CallSet: false
        Event: false
        GenomeMap: false
        MarkerPosition: false
        ObservationUnitHierarchyLevel: false
        Reference: false
        ServerInfo: false
        Variant: false
        VariantSet: false
properties:
    descriptionFormat: Property %s for type %s
    id:
        nameFormat: "%sDbId"
        link: true
        propertyFor:
            GermplasmAttribute: attributeDbId
            GermplasmAttributeValue: attributeValueDbId
            GenomeMap: mapDbId
            ObservationUnitHierarchyLevel: levelName
    name:
        nameFormat: "%sName"
        link: true
        propertyFor:
            GermplasmAttribute: attributeName
            GermplasmAttributeValue: attributeValueName
            GenomeMap: mapName
            ObservationUnitHierarchyLevel: levelName
    pui:
        nameFormat: "%sPUI"
        link: true
        propertyFor:
            GermplasmAttribute: attributePUI
            GermplasmAttributeValue: attributeValuePUI
            GenomeMap: mapPUI
    linkTypeFor:
        BreedingMethod:
            germplasm: none
            pedigreeNodes: none
        CallSet:
            calls: sub-path
        Cross:
            observationUnits: none
        CrossingProject:
            crosses: none
            plannedCrosses: none
            pedigreeNodes: none
        GeoJSON:
            image: none
            observation: none
            observationUnit: none
            germplasmOrigin: none
        Germplasm:
            sample: none
            attributeValues: none
            progenyPedigreeNodes: none
            parentPedigreeNodes: none
            siblingPedigreeNodes: none
            observations: none
            observationUnits: none
            reference: none
            referenceSet: none
        GrowthFacility:
            study: none
        Location:
            seedLots: none
            observationUnits: none
            studies: none
        OntologyTerm:
            reference: none
            referenceSet: none
        Observation:
            images: none
        ObservationUnit:
            samples: none
            events: none
            images: none
            observations: none
        ObservationVariable:
            studies: none
            observations: none
        Person:
            lists: none
            programs: none
        PlannedCross:
            crosses: none
        Program:
            crossingProjects: none
            observationUnits: none
            plates: none
            samples: none
            seedLots: none
            trials: none
        Plate:
            samples: none
        Reference:
            variant: none
        SeedLot:
            observationUnits: none
        Study:
            callSets: none
            events: none
            observations: none
            observationUnits: none
            plates: none
            samples: none
            variantSets: none
        Trial:
            contacts: embedded
            observationUnits: none
            plates: none
            samples: none
        Variant:
            calls: sub-path
        VariantSet:
            calls: sub-path
            callSets: sub-path
            variants: sub-path
controlledVocabulary:
    generate: true
    summaryFormat: Get the ${property} of ${type}
    descriptionFormat: List all available ${type} ${property}